# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bmi_cal.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(394, 285)
        self.label1 = QtWidgets.QLabel(Dialog)
        self.label1.setGeometry(QtCore.QRect(30, 70, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(Dialog)
        self.label2.setGeometry(QtCore.QRect(30, 120, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.weightinput = QtWidgets.QLineEdit(Dialog)
        self.weightinput.setGeometry(QtCore.QRect(110, 70, 113, 21))
        self.weightinput.setObjectName("weightinput")
        self.heightinput = QtWidgets.QLineEdit(Dialog)
        self.heightinput.setGeometry(QtCore.QRect(110, 120, 113, 21))
        self.heightinput.setObjectName("heightinput")
        self.exitButton = QtWidgets.QPushButton(Dialog)
        self.exitButton.setGeometry(QtCore.QRect(280, 240, 100, 32))
        self.exitButton.setObjectName("exitButton")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(150, 240, 101, 32))
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(True)
        self.pushButton.setObjectName("pushButton")
        self.label4 = QtWidgets.QLabel(Dialog)
        self.label4.setGeometry(QtCore.QRect(240, 70, 58, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.label4.setFont(font)
        self.label4.setObjectName("label4")
        self.label5 = QtWidgets.QLabel(Dialog)
        self.label5.setGeometry(QtCore.QRect(240, 120, 58, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.label5.setFont(font)
        self.label5.setObjectName("label5")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 9, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(36)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 200, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Bodoni 72 Oldstyle")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "BMI Calculator"))
        self.label1.setText(_translate("Dialog", "Weight :"))
        self.label2.setText(_translate("Dialog", "Height :"))
        self.exitButton.setText(_translate("Dialog", "Exit"))
        self.pushButton.setText(_translate("Dialog", "Calculate"))
        self.label4.setText(_translate("Dialog", "lbs "))
        self.label5.setText(_translate("Dialog", "ft (ex. 5.5)"))
        self.label.setText(_translate("Dialog", "BMI Calculator"))
        self.label_2.setText(_translate("Dialog", "This calculator is created by Austin Fang."))
